#!/usr/bin/env python3

# Developer : Hamdy Abou El Anein
# hamdy.aea@protonmail.com
# writed in python 3
# Read the readme to install the python 3 modules and dependencies
# change the picture path to your own

import sys
from easygui import *
import vlc
import json


class RadioLive:
    def __init__(self):
        self.pic_path
        self.json_path
        self.vol
        self.allradio
        self.msg
        self.image


RadioLive.vol = 50

# Picturs path, change it to your own
RadioLive.pic_path = "/home/hamdy/Documents/Radio-Streaming-Gui-Original/pictures/"
# Json file path, change it to your own
RadioLive.json_path = "/home/hamdy/Documents/Radio-Streaming-Gui-Original/"

def CodeRadio():
    player = vlc.MediaPlayer(RadioLive.allradio["CodeRadio"])
    player.play()
    RadioLive.image = RadioLive.pic_path + str("coderadio.png")
    RadioLive.msg = (
        ("You are listening Code Radio")
        + str("\n\nVolume ")
        + str(RadioLive.vol)
        + str("%")
    )
    choices = ["Exit", "Start menu", "Volume up", "Volume low"]
    reply = buttonbox(RadioLive.msg, image=RadioLive.image, choices=choices)
    if reply == "Start menu":
        player.stop()
        start()
    elif reply == "Volume up":
        if RadioLive.vol < 100:
            RadioLive.vol = RadioLive.vol + 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            CodeRadio()
        else:
            player.stop()
            CodeRadio()
    elif reply == "Volume low":
        if RadioLive.vol > 0:
            RadioLive.vol = RadioLive.vol - 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            CodeRadio()
        else:
            player.stop()
            CodeRadio()
    else:
        sys.exit(0)

def radioOrient():
    player = vlc.MediaPlayer(RadioLive.allradio["radioOrient"])
    player.play()
    RadioLive.image = RadioLive.pic_path + str("radioOrient.png")
    RadioLive.msg = (
        ("You are listening Radio Orient")
        + str("\n\nVolume ")
        + str(RadioLive.vol)
        + str("%")
    )
    choices = ["Exit", "Start menu", "Volume up", "Volume low"]
    reply = buttonbox(RadioLive.msg, image=RadioLive.image, choices=choices)
    if reply == "Start menu":
        player.stop()
        start()
    elif reply == "Volume up":
        if RadioLive.vol < 100:
            RadioLive.vol = RadioLive.vol + 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            radioOrient()
        else:
            player.stop()
            radioOrient()
    elif reply == "Volume low":
        if RadioLive.vol > 0:
            RadioLive.vol = RadioLive.vol - 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            radioOrient()
        else:
            player.stop()
            radioOrient()
    else:
        sys.exit(0)


def coranradio():
    player = vlc.MediaPlayer(RadioLive.allradio["coranradio"])
    player.play()
    RadioLive.image = RadioLive.pic_path + str("coran-radio.jpg")
    RadioLive.msg = (
        ("You are listening Radio Quran")
        + str("\n\nVolume ")
        + str(RadioLive.vol)
        + str("%")
    )
    choices = ["Exit", "Start menu", "Volume up", "Volume low"]
    reply = buttonbox(RadioLive.msg, image=RadioLive.image, choices=choices)
    if reply == "Start menu":
        player.stop()
        start()
    elif reply == "Volume up":
        if RadioLive.vol < 100:
            RadioLive.vol = RadioLive.vol + 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            coranradio()
        else:
            player.stop()
            coranradio()
    elif reply == "Volume low":
        if RadioLive.vol > 0:
            RadioLive.vol = RadioLive.vol - 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            coranradio()
        else:
            player.stop()
            coranradio()
    else:
        sys.exit(0)


def house247():
    player = vlc.MediaPlayer(RadioLive.allradio["house247"])
    player.play()
    RadioLive.image = RadioLive.pic_path + str("247house.png")
    RadioLive.msg = (
        ("You are listening the 247house radio")
        + str("\n\nVolume ")
        + str(RadioLive.vol)
        + str("%")
    )
    choices = ["Exit", "Start menu", "Volume up", "Volume low"]
    reply = buttonbox(RadioLive.msg, image=RadioLive.image, choices=choices)
    if reply == "Start menu":
        player.stop()
        start()
    elif reply == "Volume up":
        if RadioLive.vol < 100:
            RadioLive.vol = RadioLive.vol + 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            house247()
        else:
            player.stop()
            house247()
    elif reply == "Volume low":
        if RadioLive.vol > 0:
            RadioLive.vol = RadioLive.vol - 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            house247()
        else:
            player.stop()
            house247()
    else:
        sys.exit(0)


def dab247():
    player = vlc.MediaPlayer(RadioLive.allradio["dab247"])
    player.play()
    RadioLive.image = RadioLive.pic_path + str("logo247.png")
    RadioLive.msg = (
        ("You are listening the 247 Drum and Bass radio")
        + str("\n\nVolume ")
        + str(RadioLive.vol)
        + str("%")
    )
    choices = ["Exit", "Start menu", "Volume up", "Volume low"]
    reply = buttonbox(RadioLive.msg, image=RadioLive.image, choices=choices)
    if reply == "Start menu":
        player.stop()
        start()
    elif reply == "Volume up":
        if RadioLive.vol < 100:
            RadioLive.vol = RadioLive.vol + 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            dab247()
        else:
            player.stop()
            dab247()
    elif reply == "Volume low":
        if RadioLive.vol > 0:
            RadioLive.vol = RadioLive.vol - 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            dab247()
        else:
            player.stop()
            dab247()
    else:
        sys.exit(0)


def energy1058():
    player = vlc.MediaPlayer(RadioLive.allradio["energy1058"])
    player.play()
    RadioLive.image = RadioLive.pic_path + str("energy1058.jpg")
    RadioLive.msg = (
        ("You are listening the Energy 1058 radio")
        + str("\n\nVolume ")
        + str(RadioLive.vol)
        + str("%")
    )
    choices = ["Exit", "Start menu", "Volume up", "Volume low"]
    reply = buttonbox(RadioLive.msg, image=RadioLive.image, choices=choices)
    if reply == "Start menu":
        player.stop()
        start()
    elif reply == "Volume up":
        if RadioLive.vol < 100:
            RadioLive.vol = RadioLive.vol + 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            energy1058()
        else:
            player.stop()
            energy1058()
    elif reply == "Volume low":
        if RadioLive.vol > 0:
            RadioLive.vol = RadioLive.vol - 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            energy1058()
        else:
            player.stop()
            energy1058()
    else:
        sys.exit(0)


def fdlounge():
    player = vlc.MediaPlayer(RadioLive.allradio["fdlounge"])
    player.play()
    RadioLive.image = RadioLive.pic_path + str("fdlounge.jpg")
    RadioLive.msg = (
        ("You are listening FD lounge radio")
        + str("\n\nVolume ")
        + str(RadioLive.vol)
        + str("%")
    )
    choices = ["Exit", "Start menu", "Volume up", "Volume low"]
    reply = buttonbox(RadioLive.msg, image=RadioLive.image, choices=choices)
    if reply == "Start menu":
        player.stop()
        start()
    elif reply == "Volume up":
        if RadioLive.vol < 100:
            RadioLive.vol = RadioLive.vol + 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            fdlounge()
        else:
            player.stop()
            fdlounge()
    elif reply == "Volume low":
        if RadioLive.vol > 0:
            RadioLive.vol = RadioLive.vol - 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            fdlounge()
        else:
            player.stop()
            fdlounge()
    else:
        sys.exit(0)


def radiomosaique():
    player = vlc.MediaPlayer(RadioLive.allradio["radiomosaique"])
    player.audio_set_volume(RadioLive.vol)
    player.play()
    RadioLive.image = RadioLive.pic_path + str("mosaique.jpg")
    RadioLive.msg = (
        ("You are listening Mosaique FM live")
        + str("\n\nVolume ")
        + str(RadioLive.vol)
        + str("%")
    )
    choices = ["Exit", "Start menu", "Volume up", "Volume low"]
    reply = buttonbox(RadioLive.msg, image=RadioLive.image, choices=choices)
    if reply == "Start menu":
        player.stop()
        start()
    elif reply == "Volume up":
        if RadioLive.vol < 100:
            RadioLive.vol = RadioLive.vol + 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            radiomosaique()
        else:
            player.stop()
            radiomosaique()
    elif reply == "Volume low":
        if RadioLive.vol > 0:
            RadioLive.vol = RadioLive.vol - 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            radiomosaique()
        else:
            player.stop()
            radiomosaique()
    else:
        sys.exit(0)


def nrjlounge():
    player = vlc.MediaPlayer(RadioLive.allradio["nrjlounge"])
    player.play()
    RadioLive.image = RadioLive.pic_path + str("nrjlounge.jpg")
    RadioLive.msg = (
        ("You are listening to NRJ lounge radio")
        + str("\n\nVolume ")
        + str(RadioLive.vol)
        + str("%")
    )
    choices = ["Exit", "Start menu", "Volume up", "Volume low"]
    reply = buttonbox(RadioLive.msg, image=RadioLive.image, choices=choices)
    if reply == "Start menu":
        player.stop()
        start()
    elif reply == "Volume up":
        if RadioLive.vol < 100:
            RadioLive.vol = RadioLive.vol + 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            nrjlounge()
        else:
            player.stop()
            nrjlounge()
    elif reply == "Volume low":
        if RadioLive.vol > 0:
            RadioLive.vol = RadioLive.vol - 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            nrjlounge()
        else:
            player.stop()
            nrjlounge()
    else:
        sys.exit(0)


def abcpiano():
    player = vlc.MediaPlayer(RadioLive.allradio["abcpiano"])
    player.play()
    RadioLive.image = RadioLive.pic_path + str("abcpiano.jpg")
    RadioLive.msg = (
        ("You are listening ABC Piano live")
        + str("\n\nVolume ")
        + str(RadioLive.vol)
        + str("%")
    )
    choices = ["Exit", "Start menu", "Volume up", "Volume low"]
    reply = buttonbox(RadioLive.msg, image=RadioLive.image, choices=choices)
    if reply == "Start menu":
        player.stop()
        start()
    elif reply == "Volume up":
        if RadioLive.vol < 100:
            RadioLive.vol = RadioLive.vol + 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            abcpiano()
        else:
            player.stop()
            abcpiano()
    elif reply == "Volume low":
        if RadioLive.vol > 0:
            RadioLive.vol = RadioLive.vol - 10
            player.audio_set_volume(RadioLive.vol)
            player.stop()
            abcpiano()
        else:
            player.stop()
            abcpiano()
    else:
        sys.exit(0)


def start():
    RadioLive.vol = 50
    RadioLive.image = RadioLive.pic_path + str("live.jpg")
    RadioLive.msg = "Click on the button to open a live web radio"
    choices = [
        "Radio Quran",
        "Mosaique FM",
        "ABC Piano",
        "NRJ Lounge",
        "FD lounge radio",
        "Energy 1058",
        "247 House FM",
        "radio Orient","Code Radio"
    ]
    reply = buttonbox(RadioLive.msg, image=RadioLive.image, choices=choices)
    if reply == "Mosaique FM":
        radiomosaique()
    elif reply =="Code Radio":
        CodeRadio()
    elif reply == "ABC Piano":
        abcpiano()
    elif reply == "NRJ Lounge":
        nrjlounge()
    elif reply == "FD lounge radio":
        fdlounge()
    elif reply == "Energy 1058":
        energy1058()
    elif reply == "247 Drum and Bass":
        dab247()
    elif reply == "247 House FM":
        house247()
    elif reply == "Radio Quran":
        coranradio()
    elif reply == "radio Orient":
        radioOrient()
    else:
        sys.exit(0)


def parser():
    try:
        with open(RadioLive.json_path + str("radio.json"), "r") as r:
            RadioLive.allradio = json.load(r)
    except:
        print(
            "\n\n\n !!! IMPORTANT : Please verify the path of the radio.json file in the code !!!\n\n\n"
        )
        print("The actual path is : " + str(RadioLive.json_path) + str("\n\n"))
        sys.exit(1)


parser()
start()
